# -*- coding: utf-8 -*-
"""Analise_Seguranca_Bueno_Marista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIQcJ6RijFtbSNraKDvRCMjZR0u5Bnxa
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Criação da base de dados
dados = {
    "Bairro": ["Setor Bueno", "Setor Marista"],
    "Furto": [48, 32],
    "Roubo": [21, 18],
    "Perturbação": [15, 11]
}

df = pd.DataFrame(dados)

# 2. Tratamento dos dados
df["Total"] = df["Furto"] + df["Roubo"] + df["Perturbação"]

# 3. Exibição da base tratada
display(df)

# 4. Gráfico 1 - Comparação por bairro
plt.figure(figsize=(8, 5))
plt.bar(df["Bairro"], df["Total"])
plt.title("Comparação de Ocorrências por Bairro")
plt.xlabel("Bairro")
plt.ylabel("Total de Ocorrências")
plt.grid(axis="y")
plt.show()

# 5. Gráfico 2 - Distribuição por tipo de ocorrência
df_tipos = df.set_index("Bairro")[["Furto", "Roubo", "Perturbação"]]

df_tipos.T.plot(kind="bar", figsize=(8, 5))
plt.title("Distribuição por Tipo de Ocorrência")
plt.xlabel("Tipo de Ocorrência")
plt.ylabel("Quantidade")
plt.xticks(rotation=0)
plt.grid(axis="y")
plt.show()

# 6. Exportação dos dados tratados
df.to_excel("resultado_analise_seguranca.xlsx", index=False)

print("Arquivo exportado com sucesso: resultado_analise_seguranca.xlsx")